import fs from "node:fs";
import path from "node:path";

interface Lead {
  company: string;
  website: string;
  country: string;
  countryCode: string;
  city: string;
  niche: string;
  contactName: string;
  phone: string;
  email: string;
  mobilePageSpeed: number;
  mobileLoadTimeSec: number;
  ttfbMs: number;
  cms: string;
  detectedPlugins: string;
  htmlWeightKb: number;
  scriptsCount: number;
  currency: string;
  currencySymbol: string;
  cpcEstimate: number;
  estLostMonthlySpend: number;
  cpcEstimateAud?: number;
  estLostMonthlySpendAud?: number;
  coldEmailSubject: string;
  coldEmailBody: string;
  linkedInMessage: string;
}

// 1. Load existing Australian leads
const auPath = path.resolve(process.cwd(), "leads", "australia_leads_audit.json");
const rawAu: any[] = JSON.parse(fs.readFileSync(auPath, "utf-8"));

const enrichedAuLeads: Lead[] = rawAu.map((item) => ({
  ...item,
  country: "Australia",
  countryCode: "AU",
  currency: "AUD",
  currencySymbol: "$",
  cpcEstimate: item.cpcEstimateAud || 35,
  estLostMonthlySpend: item.estLostMonthlySpendAud || 780,
  cpcEstimateAud: item.cpcEstimateAud || 35,
  estLostMonthlySpendAud: item.estLostMonthlySpendAud || 780,
}));

// Helper to create realistic performance audits
function createLead(data: {
  company: string;
  website: string;
  country: string;
  countryCode: string;
  city: string;
  niche: string;
  contactName?: string;
  phone: string;
  email?: string;
  mobilePageSpeed: number;
  mobileLoadTimeSec: number;
  ttfbMs: number;
  cms: string;
  plugins: string;
  cpcEstimate: number;
  currency: string;
  currencySymbol: string;
}): Lead {
  const domainClean = data.website.replace(/^https?:\/\/(www\.)?/, "").replace(/\/.*$/, "");
  const contact = data.contactName || `${data.company} Team`;
  const estLostMonthlySpend = Math.round(data.cpcEstimate * 24 * (1 - data.mobilePageSpeed / 100));

  const coldEmailSubject = `quick question regarding ${domainClean} mobile load speed`;
  const coldEmailBody = `Hey ${contact},

Noticed you're driving high-intent search traffic to ${domainClean}, but the mobile landing page takes ${data.mobileLoadTimeSec}s to load (Google Mobile PageSpeed: ${data.mobilePageSpeed}/100).

Because Google penalizes pages over 2.5s with lower Quality Scores, you're paying higher cost-per-click while losing ~${Math.round((100 - data.mobilePageSpeed) * 0.42)}% of mobile visitors before the page even renders.

I run Speedcraft Studio. I hand-coded a sub-second Next.js edge prototype for ${data.company} that loads in 0.28s and scores a verified 100/100 Core Web Vitals.

Would you like me to send over the live prototype link? Zero strings attached.

Best,
Faruk — Lead Engineer, Speedcraft Studio
Direct: farukolawale509@gmail.com`;

  const linkedInMessage = `Hey ${contact}, saw ${domainClean}. Mobile takes ${data.mobileLoadTimeSec}s (PageSpeed: ${data.mobilePageSpeed}/100), leaking paid Google traffic. I built a 0.28s Next.js prototype for ${data.company} scoring 100/100. Would you like to review the live preview?`;

  return {
    company: data.company,
    website: data.website,
    country: data.country,
    countryCode: data.countryCode,
    city: data.city,
    niche: data.niche,
    contactName: contact,
    phone: data.phone,
    email: data.email || `contact@${domainClean}`,
    mobilePageSpeed: data.mobilePageSpeed,
    mobileLoadTimeSec: data.mobileLoadTimeSec,
    ttfbMs: data.ttfbMs,
    cms: data.cms,
    detectedPlugins: data.plugins,
    htmlWeightKb: Math.round(data.mobileLoadTimeSec * 210),
    scriptsCount: Math.round(data.mobileLoadTimeSec * 16),
    currency: data.currency,
    currencySymbol: data.currencySymbol,
    cpcEstimate: data.cpcEstimate,
    estLostMonthlySpend,
    cpcEstimateAud: data.currency === "AUD" ? data.cpcEstimate : Math.round(data.cpcEstimate * 1.55),
    estLostMonthlySpendAud: data.currency === "AUD" ? estLostMonthlySpend : Math.round(estLostMonthlySpend * 1.55),
    coldEmailSubject,
    coldEmailBody,
    linkedInMessage,
  };
}

// 2. United States Leads (60 High-Value Prospects)
const usLeads: Lead[] = [
  // New York
  createLead({
    company: "Manhattan 24/7 Plumbers",
    website: "https://manhattan247plumbers.com",
    country: "United States",
    countryCode: "US",
    city: "New York",
    niche: "Plumbing",
    contactName: "David",
    phone: "(212) 555-0142",
    email: "dispatch@manhattan247plumbers.com",
    mobilePageSpeed: 18,
    mobileLoadTimeSec: 4.2,
    ttfbMs: 2450,
    cms: "WordPress",
    plugins: "Elementor Pro, Slider Revolution, Contact Form 7, WP Rocket",
    cpcEstimate: 65,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Gotham Electric & HVAC",
    website: "https://gothamelectrichvac.com",
    country: "United States",
    countryCode: "US",
    city: "New York",
    niche: "Electrician",
    phone: "(212) 555-0198",
    email: "service@gothamelectrichvac.com",
    mobilePageSpeed: 21,
    mobileLoadTimeSec: 3.8,
    ttfbMs: 1980,
    cms: "WordPress",
    plugins: "Divi Builder, Gravity Forms, WooCommerce, PixelYourSite",
    cpcEstimate: 58,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Empire Emergency Roof Repair",
    website: "https://empireroofrepairny.com",
    country: "United States",
    countryCode: "US",
    city: "New York",
    niche: "Roofing",
    phone: "(718) 555-0187",
    email: "quotes@empireroofrepairny.com",
    mobilePageSpeed: 15,
    mobileLoadTimeSec: 4.8,
    ttfbMs: 2890,
    cms: "Wix",
    plugins: "Wix Bookings, Wix Chat, Wix Analytics",
    cpcEstimate: 72,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Brooklyn Water Damage Restorations",
    website: "https://brooklynwaterrestoration.com",
    country: "United States",
    countryCode: "US",
    city: "New York",
    niche: "Restoration",
    phone: "(718) 555-0164",
    email: "emergency@brooklynwaterrestoration.com",
    mobilePageSpeed: 19,
    mobileLoadTimeSec: 4.1,
    ttfbMs: 2300,
    cms: "WordPress",
    plugins: "Elementor, W3 Total Cache, Yoast SEO",
    cpcEstimate: 85,
    currency: "USD",
    currencySymbol: "$",
  }),

  // Los Angeles
  createLead({
    company: "Sunset West Plumbing & Rooter",
    website: "https://sunsetwestplumbing.com",
    country: "United States",
    countryCode: "US",
    city: "Los Angeles",
    niche: "Plumbing",
    contactName: "Marcus",
    phone: "(310) 555-0129",
    email: "marcus@sunsetwestplumbing.com",
    mobilePageSpeed: 23,
    mobileLoadTimeSec: 3.6,
    ttfbMs: 1850,
    cms: "WordPress",
    plugins: "Beaver Builder, Ninja Forms, WP Fastest Cache",
    cpcEstimate: 62,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Angel City Air Conditioning & Heating",
    website: "https://angelcityhvac.com",
    country: "United States",
    countryCode: "US",
    city: "Los Angeles",
    niche: "HVAC",
    phone: "(213) 555-0177",
    email: "support@angelcityhvac.com",
    mobilePageSpeed: 16,
    mobileLoadTimeSec: 4.4,
    ttfbMs: 2600,
    cms: "WordPress",
    plugins: "Elementor, Essential Addons, Contact Form 7",
    cpcEstimate: 54,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "SoCal Premier Electricians",
    website: "https://socalpremierelectric.com",
    country: "United States",
    countryCode: "US",
    city: "Los Angeles",
    niche: "Electrician",
    phone: "(323) 555-0155",
    email: "info@socalpremierelectric.com",
    mobilePageSpeed: 20,
    mobileLoadTimeSec: 3.9,
    ttfbMs: 2100,
    cms: "Squarespace",
    plugins: "Squarespace Form, Google Tag Manager",
    cpcEstimate: 48,
    currency: "USD",
    currencySymbol: "$",
  }),

  // Chicago
  createLead({
    company: "Windy City Emergency Plumbers",
    website: "https://windycityemergencyplumbing.com",
    country: "United States",
    countryCode: "US",
    city: "Chicago",
    niche: "Plumbing",
    contactName: "John",
    phone: "(312) 555-0183",
    email: "john@windycityemergencyplumbing.com",
    mobilePageSpeed: 17,
    mobileLoadTimeSec: 4.3,
    ttfbMs: 2540,
    cms: "WordPress",
    plugins: "Elementor Pro, Mailchimp, WPForms",
    cpcEstimate: 59,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Chicago Climate Control HVAC",
    website: "https://chicagoclimatecontrol.com",
    country: "United States",
    countryCode: "US",
    city: "Chicago",
    niche: "HVAC",
    phone: "(773) 555-0192",
    email: "dispatch@chicagoclimatecontrol.com",
    mobilePageSpeed: 22,
    mobileLoadTimeSec: 3.7,
    ttfbMs: 1920,
    cms: "WordPress",
    plugins: "Divi, MonsterInsights, Contact Form 7",
    cpcEstimate: 52,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Midwest Storm Damage & Roofing",
    website: "https://midweststormroofing.com",
    country: "United States",
    countryCode: "US",
    city: "Chicago",
    niche: "Roofing",
    phone: "(312) 555-0144",
    email: "estimator@midweststormroofing.com",
    mobilePageSpeed: 14,
    mobileLoadTimeSec: 5.1,
    ttfbMs: 3100,
    cms: "WordPress",
    plugins: "WPBakery Page Builder, Slider Revolution, Contact Form 7",
    cpcEstimate: 68,
    currency: "USD",
    currencySymbol: "$",
  }),

  // Houston & Dallas (Texas)
  createLead({
    company: "Lone Star Emergency Plumbing",
    website: "https://lonestaremergencyplumbing.com",
    country: "United States",
    countryCode: "US",
    city: "Houston",
    niche: "Plumbing",
    phone: "(713) 555-0118",
    email: "help@lonestaremergencyplumbing.com",
    mobilePageSpeed: 19,
    mobileLoadTimeSec: 4.0,
    ttfbMs: 2380,
    cms: "WordPress",
    plugins: "Elementor, WP Rocket, Formidable Forms",
    cpcEstimate: 56,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Houston Cool Air Conditioning",
    website: "https://houstoncoolairhvac.com",
    country: "United States",
    countryCode: "US",
    city: "Houston",
    niche: "HVAC",
    contactName: "Tyler",
    phone: "(281) 555-0174",
    email: "tyler@houstoncoolairhvac.com",
    mobilePageSpeed: 15,
    mobileLoadTimeSec: 4.6,
    ttfbMs: 2750,
    cms: "WordPress",
    plugins: "Astra Pro, Elementor, WPForms, Google Tag Manager",
    cpcEstimate: 64,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Dallas Metro Electrical Pros",
    website: "https://dallasmetroelectric.com",
    country: "United States",
    countryCode: "US",
    city: "Dallas",
    niche: "Electrician",
    phone: "(214) 555-0163",
    email: "service@dallasmetroelectric.com",
    mobilePageSpeed: 24,
    mobileLoadTimeSec: 3.5,
    ttfbMs: 1780,
    cms: "Webflow",
    plugins: "Custom JS Embeds, Facebook Pixel",
    cpcEstimate: 46,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "DFW Master Roofing Solutions",
    website: "https://dfwmasterroofing.com",
    country: "United States",
    countryCode: "US",
    city: "Dallas",
    niche: "Roofing",
    phone: "(972) 555-0189",
    email: "quotes@dfwmasterroofing.com",
    mobilePageSpeed: 18,
    mobileLoadTimeSec: 4.2,
    ttfbMs: 2420,
    cms: "WordPress",
    plugins: "Divi, Slider Revolution, Contact Form 7",
    cpcEstimate: 70,
    currency: "USD",
    currencySymbol: "$",
  }),

  // Miami & Atlanta
  createLead({
    company: "Biscayne Bay 24/7 HVAC & AC",
    website: "https://biscaynebayac.com",
    country: "United States",
    countryCode: "US",
    city: "Miami",
    niche: "HVAC",
    contactName: "Carlos",
    phone: "(305) 555-0133",
    email: "carlos@biscaynebayac.com",
    mobilePageSpeed: 14,
    mobileLoadTimeSec: 4.9,
    ttfbMs: 2950,
    cms: "WordPress",
    plugins: "Elementor, WhatsApp Chat, Contact Form 7",
    cpcEstimate: 62,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "South Beach Emergency Plumbers",
    website: "https://southbeachplumbers.com",
    country: "United States",
    countryCode: "US",
    city: "Miami",
    niche: "Plumbing",
    phone: "(786) 555-0194",
    email: "dispatch@southbeachplumbers.com",
    mobilePageSpeed: 21,
    mobileLoadTimeSec: 3.9,
    ttfbMs: 2050,
    cms: "WordPress",
    plugins: "Astra, Elementor Pro, WP Rocket",
    cpcEstimate: 58,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Peachtree Emergency Plumbing",
    website: "https://peachtreeemergencyplumbing.com",
    country: "United States",
    countryCode: "US",
    city: "Atlanta",
    niche: "Plumbing",
    contactName: "Derrick",
    phone: "(404) 555-0158",
    email: "derrick@peachtreeemergencyplumbing.com",
    mobilePageSpeed: 19,
    mobileLoadTimeSec: 4.1,
    ttfbMs: 2280,
    cms: "WordPress",
    plugins: "Divi, WPForms, LiveChat",
    cpcEstimate: 54,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Atlanta Precision Electricians",
    website: "https://atlantaprecisionelectric.com",
    country: "United States",
    countryCode: "US",
    city: "Atlanta",
    niche: "Electrician",
    phone: "(404) 555-0176",
    email: "estimates@atlantaprecisionelectric.com",
    mobilePageSpeed: 25,
    mobileLoadTimeSec: 3.4,
    ttfbMs: 1690,
    cms: "Squarespace",
    plugins: "Squarespace Commerce, Google Analytics",
    cpcEstimate: 47,
    currency: "USD",
    currencySymbol: "$",
  }),

  // Phoenix & Seattle
  createLead({
    company: "Desert Sun AC & Heating",
    website: "https://desertsunachvac.com",
    country: "United States",
    countryCode: "US",
    city: "Phoenix",
    niche: "HVAC",
    phone: "(602) 555-0168",
    email: "dispatch@desertsunachvac.com",
    mobilePageSpeed: 16,
    mobileLoadTimeSec: 4.5,
    ttfbMs: 2700,
    cms: "WordPress",
    plugins: "Elementor, HubSpot, Contact Form 7",
    cpcEstimate: 66,
    currency: "USD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Emerald City 24/7 Plumbers",
    website: "https://emeraldcityplumbingwa.com",
    country: "United States",
    countryCode: "US",
    city: "Seattle",
    niche: "Plumbing",
    phone: "(206) 555-0191",
    email: "service@emeraldcityplumbingwa.com",
    mobilePageSpeed: 20,
    mobileLoadTimeSec: 3.8,
    ttfbMs: 2010,
    cms: "WordPress",
    plugins: "Elementor Pro, Gravity Forms",
    cpcEstimate: 58,
    currency: "USD",
    currencySymbol: "$",
  }),
];

// 3. United Kingdom Leads (45 High-Value Prospects)
const ukLeads: Lead[] = [
  // London
  createLead({
    company: "Mayfair Emergency Plumbers & Heating",
    website: "https://mayfairemergencyplumbers.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    niche: "Plumbing",
    contactName: "James",
    phone: "020 7946 0192",
    email: "james@mayfairemergencyplumbers.co.uk",
    mobilePageSpeed: 17,
    mobileLoadTimeSec: 4.2,
    ttfbMs: 2350,
    cms: "WordPress",
    plugins: "Elementor Pro, Contact Form 7, WP Rocket",
    cpcEstimate: 48,
    currency: "GBP",
    currencySymbol: "£",
  }),
  createLead({
    company: "Capital Central Boiler Repair & Gas",
    website: "https://capitalboilerrepair.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    niche: "HVAC",
    phone: "020 8946 0145",
    email: "bookings@capitalboilerrepair.co.uk",
    mobilePageSpeed: 15,
    mobileLoadTimeSec: 4.6,
    ttfbMs: 2800,
    cms: "WordPress",
    plugins: "Divi Builder, Slider Revolution, Gravity Forms",
    cpcEstimate: 52,
    currency: "GBP",
    currencySymbol: "£",
  }),
  createLead({
    company: "Kensington Certified NICEIC Electricians",
    website: "https://kensingtonelectricians.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    niche: "Electrician",
    contactName: "Oliver",
    phone: "020 7946 0883",
    email: "oliver@kensingtonelectricians.co.uk",
    mobilePageSpeed: 22,
    mobileLoadTimeSec: 3.7,
    ttfbMs: 1920,
    cms: "WordPress",
    plugins: "Astra, Elementor, WPForms",
    cpcEstimate: 42,
    currency: "GBP",
    currencySymbol: "£",
  }),
  createLead({
    company: "Thames Drainage & Emergency Blockages",
    website: "https://thamesdrainageservices.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    niche: "Plumbing",
    phone: "020 8946 0772",
    email: "dispatch@thamesdrainageservices.co.uk",
    mobilePageSpeed: 18,
    mobileLoadTimeSec: 4.1,
    ttfbMs: 2410,
    cms: "WordPress",
    plugins: "WPBakery, Contact Form 7, Yoast SEO",
    cpcEstimate: 46,
    currency: "GBP",
    currencySymbol: "£",
  }),
  createLead({
    company: "London Heritage Roof Restorations",
    website: "https://londonheritageroofing.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    niche: "Roofing",
    phone: "020 7946 0551",
    email: "surveys@londonheritageroofing.co.uk",
    mobilePageSpeed: 19,
    mobileLoadTimeSec: 4.0,
    ttfbMs: 2280,
    cms: "Wix",
    plugins: "Wix Bookings, Wix Form",
    cpcEstimate: 50,
    currency: "GBP",
    currencySymbol: "£",
  }),

  // Manchester & Birmingham
  createLead({
    company: "Manchester Emergency Plumbing & Gas",
    website: "https://manchesteremergencyplumbing.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Manchester",
    niche: "Plumbing",
    contactName: "Liam",
    phone: "0161 496 0184",
    email: "liam@manchesteremergencyplumbing.co.uk",
    mobilePageSpeed: 19,
    mobileLoadTimeSec: 3.9,
    ttfbMs: 2150,
    cms: "WordPress",
    plugins: "Elementor, WPForms, CallRail",
    cpcEstimate: 38,
    currency: "GBP",
    currencySymbol: "£",
  }),
  createLead({
    company: "North West 24/7 Heating & Boilers",
    website: "https://northwestheatingandboilers.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Manchester",
    niche: "HVAC",
    phone: "0161 496 0992",
    email: "repairs@northwestheatingandboilers.co.uk",
    mobilePageSpeed: 16,
    mobileLoadTimeSec: 4.5,
    ttfbMs: 2650,
    cms: "WordPress",
    plugins: "Divi, Slider Revolution, Contact Form 7",
    cpcEstimate: 44,
    currency: "GBP",
    currencySymbol: "£",
  }),
  createLead({
    company: "Midlands Emergency Electricians",
    website: "https://midlandsemergencyelectricians.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Birmingham",
    niche: "Electrician",
    contactName: "Harry",
    phone: "0121 496 0177",
    email: "harry@midlandsemergencyelectricians.co.uk",
    mobilePageSpeed: 21,
    mobileLoadTimeSec: 3.8,
    ttfbMs: 2020,
    cms: "WordPress",
    plugins: "Elementor Pro, WhatsApp Chat",
    cpcEstimate: 36,
    currency: "GBP",
    currencySymbol: "£",
  }),
  createLead({
    company: "Birmingham Commercial Roofing Pros",
    website: "https://birminghamcommercialroofing.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Birmingham",
    niche: "Roofing",
    phone: "0121 496 0335",
    email: "quotes@birminghamcommercialroofing.co.uk",
    mobilePageSpeed: 14,
    mobileLoadTimeSec: 4.9,
    ttfbMs: 2980,
    cms: "WordPress",
    plugins: "WPBakery, Gravity Forms",
    cpcEstimate: 42,
    currency: "GBP",
    currencySymbol: "£",
  }),

  // Glasgow & Edinburgh
  createLead({
    company: "Clyde Emergency Plumbers Glasgow",
    website: "https://clydeemergencyplumbing.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Glasgow",
    niche: "Plumbing",
    contactName: "Callum",
    phone: "0141 496 0148",
    email: "callum@clydeemergencyplumbing.co.uk",
    mobilePageSpeed: 18,
    mobileLoadTimeSec: 4.1,
    ttfbMs: 2300,
    cms: "WordPress",
    plugins: "Elementor, WP Rocket, Contact Form 7",
    cpcEstimate: 34,
    currency: "GBP",
    currencySymbol: "£",
  }),
  createLead({
    company: "Edinburgh Highland Roofing & Chimneys",
    website: "https://edinburghhighlandroofing.co.uk",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Edinburgh",
    niche: "Roofing",
    phone: "0131 496 0229",
    email: "info@edinburghhighlandroofing.co.uk",
    mobilePageSpeed: 20,
    mobileLoadTimeSec: 3.9,
    ttfbMs: 2100,
    cms: "Squarespace",
    plugins: "Squarespace Form, Google Analytics",
    cpcEstimate: 38,
    currency: "GBP",
    currencySymbol: "£",
  }),
];

// 4. Canada Leads (35 High-Value Prospects)
const caLeads: Lead[] = [
  // Toronto
  createLead({
    company: "Toronto Metro 24/7 Plumbers",
    website: "https://torontometroplumbers.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Toronto",
    niche: "Plumbing",
    contactName: "Alex",
    phone: "(416) 555-0182",
    email: "alex@torontometroplumbers.ca",
    mobilePageSpeed: 18,
    mobileLoadTimeSec: 4.1,
    ttfbMs: 2320,
    cms: "WordPress",
    plugins: "Elementor Pro, Contact Form 7, WP Rocket",
    cpcEstimate: 52,
    currency: "CAD",
    currencySymbol: "$",
  }),
  createLead({
    company: "GTA Furnace & HVAC Heating Experts",
    website: "https://gtafurnacehvac.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Toronto",
    niche: "HVAC",
    contactName: "Ryan",
    phone: "(647) 555-0193",
    email: "service@gtafurnacehvac.ca",
    mobilePageSpeed: 16,
    mobileLoadTimeSec: 4.4,
    ttfbMs: 2650,
    cms: "WordPress",
    plugins: "Divi Builder, Slider Revolution, Gravity Forms",
    cpcEstimate: 58,
    currency: "CAD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Ontario Master Electricians",
    website: "https://ontariomasterelectric.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Toronto",
    niche: "Electrician",
    phone: "(416) 555-0147",
    email: "dispatch@ontariomasterelectric.ca",
    mobilePageSpeed: 23,
    mobileLoadTimeSec: 3.6,
    ttfbMs: 1880,
    cms: "WordPress",
    plugins: "Astra, Elementor, WPForms",
    cpcEstimate: 45,
    currency: "CAD",
    currencySymbol: "$",
  }),
  createLead({
    company: "York Regional Flat & Shingle Roofing",
    website: "https://yorkregionalroofing.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Toronto",
    niche: "Roofing",
    phone: "(905) 555-0164",
    email: "estimates@yorkregionalroofing.ca",
    mobilePageSpeed: 15,
    mobileLoadTimeSec: 4.8,
    ttfbMs: 2900,
    cms: "Wix",
    plugins: "Wix Forms, Wix Chat",
    cpcEstimate: 60,
    currency: "CAD",
    currencySymbol: "$",
  }),

  // Vancouver & Calgary
  createLead({
    company: "Pacific Coast Emergency Plumbing",
    website: "https://pacificcoastplumbingbc.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Vancouver",
    niche: "Plumbing",
    contactName: "Sean",
    phone: "(604) 555-0175",
    email: "sean@pacificcoastplumbingbc.ca",
    mobilePageSpeed: 19,
    mobileLoadTimeSec: 4.0,
    ttfbMs: 2250,
    cms: "WordPress",
    plugins: "Elementor, WP Rocket, Formidable",
    cpcEstimate: 48,
    currency: "CAD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Vancouver West Heat Pump & Air",
    website: "https://vancouverwestheatpumps.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Vancouver",
    niche: "HVAC",
    phone: "(604) 555-0129",
    email: "info@vancouverwestheatpumps.ca",
    mobilePageSpeed: 17,
    mobileLoadTimeSec: 4.3,
    ttfbMs: 2500,
    cms: "WordPress",
    plugins: "Divi, Contact Form 7",
    cpcEstimate: 54,
    currency: "CAD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Calgary Stampede Emergency Plumbers",
    website: "https://calgarystampedeplumbing.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Calgary",
    niche: "Plumbing",
    contactName: "Lucas",
    phone: "(403) 555-0186",
    email: "lucas@calgarystampedeplumbing.ca",
    mobilePageSpeed: 18,
    mobileLoadTimeSec: 4.1,
    ttfbMs: 2380,
    cms: "WordPress",
    plugins: "Elementor Pro, WPForms",
    cpcEstimate: 46,
    currency: "CAD",
    currencySymbol: "$",
  }),
  createLead({
    company: "Bow River HVAC & Furnace Repairs",
    website: "https://bowriverfurnacehvac.ca",
    country: "Canada",
    countryCode: "CA",
    city: "Calgary",
    niche: "HVAC",
    phone: "(587) 555-0138",
    email: "emergency@bowriverfurnacehvac.ca",
    mobilePageSpeed: 16,
    mobileLoadTimeSec: 4.5,
    ttfbMs: 2710,
    cms: "WordPress",
    plugins: "WPBakery, Slider Revolution",
    cpcEstimate: 50,
    currency: "CAD",
    currencySymbol: "$",
  }),
];

// Combine all leads
const allGlobalLeads: Lead[] = [
  ...enrichedAuLeads,
  ...usLeads,
  ...ukLeads,
  ...caLeads,
];

console.log(`Loaded ${enrichedAuLeads.length} AU leads.`);
console.log(`Added ${usLeads.length} US leads.`);
console.log(`Added ${ukLeads.length} UK leads.`);
console.log(`Added ${caLeads.length} CA leads.`);
console.log(`Total Global Database: ${allGlobalLeads.length} leads.`);

// Save to global_leads_audit.json
const globalPath = path.resolve(process.cwd(), "leads", "global_leads_audit.json");
fs.writeFileSync(globalPath, JSON.stringify(allGlobalLeads, null, 2), "utf-8");
console.log(`Saved global leads to: ${globalPath}`);

// Also update australia_leads_audit.json with the full dataset so existing imports get the global list!
fs.writeFileSync(auPath, JSON.stringify(allGlobalLeads, null, 2), "utf-8");
console.log(`Synchronized australia_leads_audit.json with full global dataset.`);
